spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:user_management_system}?useSSL=true&requireSSL=true&verifyServerCertificate=false
    username:  ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:#Rahul2004}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 8080
